
name: Run GitHub Action
on: 
  push: 
  workflow_dispatch: 
jobs: 
  UseIrregularAction: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use Irregular Action
        uses: StartAutomating/Irregular@master
        id: Irregular

